default_platform(:ios)

platform :ios do
  desc "Runs unit tests"
  lane :tests do
    params = {
      package_path: '.',
      scheme: 'LongfellowZkp',
      devices: ['iPhone Air'],
      result_bundle: true
    }

    if ENV['CI']
      params[:xcargs] = '-skipPackagePluginValidation -skipMacroValidation'
    end

    run_tests(params)
  end

  desc "Code coverage"
  lane :code_coverage do
    FileUtils.remove_dir '../xcov_output', true

    params = {
      package_path: '.',
      scheme: 'LongfellowZkp',
      devices: ['iPhone Air'],
      output_directory: 'xcov_output',
      result_bundle: true,
      code_coverage: true,
      parallel_testing: false,
      xcodebuild_formatter: 'xcbeautify'
    }

    if ENV['CI']
      params[:xcargs] = '-skipPackagePluginValidation -skipMacroValidation'
    end

    run_tests(params)

    xcov(
      scheme: 'LongfellowZkp',
      output_directory: 'xcov_output',
      is_swift_package: true,
      minimum_coverage_percentage: 50.0,
      include_targets: 'LongfellowZkp'
    )

    if ENV['CI'] != 'true'
      sh 'open ../xcov_output/index.html'
    end
  end
end
